export enum ActionTypes {
  login = "login",
  logout = "logout",
  getUserInfo = "getUserInfo",
  getAnnouncements = "getAnnouncements",
  getBanners = "getBanners",
  getLocation = "getLocation",
  getCount = "getCount",
  getMyMissions = "getMyMissions",
  getMyUncheckedMissions = "getMyUncheckedMissions",
  acceptMission = "acceptMission",
  refuseMission = "refuseMission",
  initCurrentMission = "initCurrentMission",
  clearCurrentMission = "clearCurrentMission",
  getCurrentMissionInfo = "getCurrentMissionInfo",
  getCurrentMissionMembers = "getCurrentMissionMembers",
  onMessageEvent = "onMessageEvent",
  getMessageList = "getMessageList",
  checkoutConversation = "checkoutConversation",
}
