export enum MutationTypes {
  SET_LOGIN = "SET_LOGIN",
  SET_USER_INFO = "SET_USER_INFO",
  SET_AVATAR_PATH = "SET_AVATAR_PATH",
  SET_ANNOUNCEMENT_LIST = "SET_ANNOUNCEMENT_LIST",
  SET_BANNER_LIST = "SET_BANNER_LIST",
  SET_LOCATION = "SET_LOCATION",
  SET_COUNT = "SET_COUNT",
  SET_MY_MISSIONS = "SET_MY_MISSIONS",
  SET_MY_UNCHECKED_MISSIONS = "SET_MY_UNCHECKED_MISSIONS",
  SET_CURRENT_MISSION = "SET_CURRENT_MISSION",
}
