export enum MutationTypes {
  SET_LOGIN = "SET_LOGIN",
  SET_USER_INFO = "SET_USER_INFO",
  SET_AVATAR_PATH = "SET_AVATAR_PATH",
  SET_ANNOUNCEMENT_LIST = "SET_ANNOUNCEMENT_LIST",
  SET_BANNER_LIST = "SET_BANNER_LIST",
  SET_LOCATION = "SET_LOCATION",
  SET_COUNT = "SET_COUNT",
}
