/* eslint-disable */
// @ts-nocheck
// generated by free-swagger-client

export type JavaMap<T, U> = Record<string, U>;

export type JavaList<T> = Array<T>;
export interface ResponseData<T> {
  data?: T; // 返回数据
  message?: string; // 状态信息
  refreshToken?: string; // refreshToken
  state?: number; // 状态码
  token?: string; // accessToken
}
export interface Admin {
  city?: string; // 管理员管辖区所在市
  district?: string; // 管理员管辖区
  id?: number; // 管理员ID
  password?: string;
  province?: string; // 管理员管辖区所在省
  role?: string; // 管理员角色
  roleId?: number; // 管理员角色ID
  userName?: string;
}
export interface BindVolunteerInformation {
  IDCard?: string; // 身份证号
  name?: string; // 姓名
}
export interface Case {
  address?: string;
  city?: string;
  district?: string;
  family?: Family;
  id?: number;
  latitude?: number;
  longitude?: number;
  oldMan?: OldMan;
  others?: string;
  place?: string;
  time?: Timestamp;
  volunteers?: Volunteer[];
}
export interface Family {
  avatarUrl?: string; // 头像
  city?: string; // 城市
  country?: string; // 国家
  id?: number; // 家属ID
  name?: string; // 姓名
  nickName?: string; // 昵称
  phone?: string; // 手机号
  province?: string; // 省份
  sex?: number; // 性别
  state?: number; // 账号状态
}
export interface FamilyInformation {
  code?: string; // 短信验证码
  name?: string; // 姓名
  phone?: string; // 手机号
}
export interface FamilyLoginCode {
  code?: string; // 从微信获取的code
}
export interface FamilyRefreshToken {
  refreshToken?: string; // refreshToken
}
export interface FamilyUserinfo {
  encryptedData?: string; // 加密字符串
  iv?: string; // 从微信获取的iv
}
export interface OldMan {
  address?: string; // 详细地址
  age?: number;
  cases?: Case[];
  city?: string; // 城市
  disability?: string;
  district?: string; // 区
  family?: Family;
  figure?: string;
  height?: number;
  id?: number;
  idcard?: string;
  identificationPhoto?: string;
  lifePhoto?: string;
  name?: string;
  offerPlace?: string;
  otherFeature?: string;
  otherIllness?: string;
  others?: string;
  phone?: string;
  province?: string; // 省份
  senileDementia?: number;
  sex?: number;
  weight?: number;
}
export interface Timestamp {
  date?: number;
  day?: number;
  hours?: number;
  minutes?: number;
  month?: number;
  nanos?: number;
  seconds?: number;
  time?: number;
  timezoneOffset?: number;
  year?: number;
}
export interface Volunteer {
  avatarUrl?: string; // 头像
  cases?: Case[];
  encryptedData?: string;
  id?: number; // 志愿者ID
  information?: VolunteerInformation;
  iv?: string;
  nickName?: string; // 昵称
  phone?: string; // 手机号
  state?: number; // 用户状态
}
export interface VolunteerBindPhone {
  code?: string; // 验证码
  phone?: string; // 手机号
}
export interface VolunteerInformation {
  address?: string; // 详细地址
  city?: string; // 城市
  country?: string; // 国家
  district?: string; // 区
  id?: number; // ID
  idcard?: string;
  name?: string; // 姓名
  province?: string; // 省份
  sex?: number; // 性别
  volunteerId?: number;
}
export interface VolunteerLoginCode {
  code?: string; // 从微信获取的code
}
export interface VolunteerRefreshToken {
  refreshToken?: string; // refreshToken
}
export interface volunteerUserInfo {
  encryptedData?: string; // 加密字符串
  iv?: string; // 从微信获取的iv
}
export interface zzzzzzzzzzzzzzz {
  encryptedData?: string; // 加密字符串
  iv?: string; // 从微信获取的iv
}
